version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-checksite
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana-checksite
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  mariadb_data:
  grafana_data:
